import Head from 'next/head';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Fida Shnakher|Frontend Developer</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main >
        <section className='min-h-screen'>
          <nav>
            <h1>Fida Shnakher|Frontend Developer</h1>
            <ul>
             <li></li>
             <li><a href="../public/Fida-Sh-CV-FrontEnd.pdf">Resume</a></li> 
            </ul>
          </nav>
        </section>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}
