import Head from 'next/head';
import { BsFillMoonStarsFill }from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub}from 'react-icons/ai';
import Image from 'next/image';
import myPic from '../public/Images/me.png';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Fida Shnakher|Frontend Developer</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Developed by</h1>
            <ul className='flex items-center'>
             <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
             <li><a className='bg-gradient-to-r from-purple-400 to-teal-300 text-white font-burtons px-8 py-2 rounded-3xl text-lg ml-8 ' href="../public/Fida-Sh-CV-FrontEnd.pdf">Resume</a></li> 
            </ul>
          </nav>
          <div className='text-center p10'>
            <h2 className='text-4xl py-2 text-teal-500 font-medium'>Fida Shnakher</h2>
            <h3 className='text-2xl py-2'>Frontend Developer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Harum cum laborum in sequi officia ab laboriosam tenetur mollitia reprehenderit maxime repudiandae, optio voluptatum, quas quasi dolore repellat enim explicabo quisquam!</p>
          </div>
          <div className='text-5xl flex justify-center gap-20 py-3 '>
           <a className='bg-gradient-to-r from-purple-400 to-teal-300 ' href="https://www.linkedin.com/in/fida-shnakher-0b0b4a1b5"><AiFillLinkedin /></a>
           <a className='bg-gradient-to-r from-purple-400 to-teal-300' href="https://github.com/fidashn"><AiFillGithub/></a>
          </div>

          <div className='relative mx-auto bg-gradient-to-r from-purple-400 to-teal-300 rounded-full w-80 h-80 mt-20'>
            <Image alt='' src={myPic} layout="fill" objectFit="cover" className='rounded-full w-80 h-80'/>
          </div>
          
        </section>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}
